//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelfInstallingWindowsServiceAdmin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SelfInstallingWindowsServiceAdmin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uninstallService.bat.
        /// </summary>
        internal static string AppDependency_1 {
            get {
                return ResourceManager.GetString("AppDependency_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SampleExtension.dll.
        /// </summary>
        internal static string AppDependency_2 {
            get {
                return ResourceManager.GetString("AppDependency_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelfInstallingWindowsServiceAdmin.Assemblies..
        /// </summary>
        internal static string DependencyPrefix {
            get {
                return ResourceManager.GetString("DependencyPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self-installing Windows Service.
        /// </summary>
        internal static string SERVICE_DESCRIPTION {
            get {
                return ResourceManager.GetString("SERVICE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self-installing Windows Service.
        /// </summary>
        internal static string SERVICE_DISPLAY_NAME {
            get {
                return ResourceManager.GetString("SERVICE_DISPLAY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self-installing Windows Service.
        /// </summary>
        internal static string SERVICE_NAME {
            get {
                return ResourceManager.GetString("SERVICE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE ServiceStatus ( 
        ///    ServiceStatus            INTEGER     NOT NULL,
        ///    ServiceStatusDescription TEXT( 20 )  NOT NULL,
        ///    PRIMARY KEY ( ServiceStatus ) 
        ///);.
        /// </summary>
        internal static string SERVICE_STATUS_DB_SETUP_1 {
            get {
                return ResourceManager.GetString("SERVICE_STATUS_DB_SETUP_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into ServiceStatus(ServiceStatus, ServiceStatusDescription) values (7, &quot;Paused&quot;).
        /// </summary>
        internal static string SERVICE_STATUS_DB_SETUP_10 {
            get {
                return ResourceManager.GetString("SERVICE_STATUS_DB_SETUP_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into ServiceStatus(ServiceStatus, ServiceStatusDescription) values (10, &quot;PerformingAction&quot;).
        /// </summary>
        internal static string SERVICE_STATUS_DB_SETUP_11 {
            get {
                return ResourceManager.GetString("SERVICE_STATUS_DB_SETUP_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE ServiceMonitor ( 
        ///    ServiceId             INTEGER  NOT NULL,
        ///    MonitorTime           DATETIME,
        ///    ServiceSuccessRunTime DATETIME,
        ///    ServiceFailRunTime    DATETIME,
        ///    FOREIGN KEY ( ServiceId ) REFERENCES Service ( ServiceId ) 
        ///);.
        /// </summary>
        internal static string SERVICE_STATUS_DB_SETUP_12 {
            get {
                return ResourceManager.GetString("SERVICE_STATUS_DB_SETUP_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE Service ( 
        ///    ServiceId     INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
        ///    ServiceStatus INTEGER NOT NULL,
        ///    ServiceName TEXT(100) NOT NULL,
        ///    ServiceDescription TEXT(1000) NOT NULL,
        ///    ServiceDisplayName TEXT(100) NOT NULL,
        ///    LocationId    INTEGER NOT NULL,
        ///    SystemId      INTEGER NOT NULL,
        ///    ApplicationId INTEGER NOT NULL,	
        ///    InstallPath TEXT( 512 ) NOT NULL,
        ///    IsHub              BOOLEAN       NOT NULL,
        ///    FOREIGN KEY ( ServiceStatus ) REFERENCES ServiceStatus ( S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SERVICE_STATUS_DB_SETUP_2 {
            get {
                return ResourceManager.GetString("SERVICE_STATUS_DB_SETUP_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE ServiceCommand ( 
        ///    ServiceId          INTEGER       NOT NULL,
        ///    CommandId          INTEGER       NOT NULL,
        ///    CommandDescription TEXT( 1000 )  NOT NULL,
        ///    PRIMARY KEY ( ServiceId, CommandId ),
        ///    FOREIGN KEY ( ServiceId ) REFERENCES Service ( ServiceId ) 
        ///);.
        /// </summary>
        internal static string SERVICE_STATUS_DB_SETUP_3 {
            get {
                return ResourceManager.GetString("SERVICE_STATUS_DB_SETUP_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into ServiceStatus(ServiceStatus, ServiceStatusDescription) values (1, &quot;Stopped&quot;).
        /// </summary>
        internal static string SERVICE_STATUS_DB_SETUP_4 {
            get {
                return ResourceManager.GetString("SERVICE_STATUS_DB_SETUP_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into ServiceStatus(ServiceStatus, ServiceStatusDescription) values (2, &quot;StartPending&quot;).
        /// </summary>
        internal static string SERVICE_STATUS_DB_SETUP_5 {
            get {
                return ResourceManager.GetString("SERVICE_STATUS_DB_SETUP_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into ServiceStatus(ServiceStatus, ServiceStatusDescription) values (3, &quot;StopPending&quot;).
        /// </summary>
        internal static string SERVICE_STATUS_DB_SETUP_6 {
            get {
                return ResourceManager.GetString("SERVICE_STATUS_DB_SETUP_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into ServiceStatus(ServiceStatus, ServiceStatusDescription) values (4, &quot;Running&quot;).
        /// </summary>
        internal static string SERVICE_STATUS_DB_SETUP_7 {
            get {
                return ResourceManager.GetString("SERVICE_STATUS_DB_SETUP_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into ServiceStatus(ServiceStatus, ServiceStatusDescription) values (5, &quot;ContinuePending&quot;).
        /// </summary>
        internal static string SERVICE_STATUS_DB_SETUP_8 {
            get {
                return ResourceManager.GetString("SERVICE_STATUS_DB_SETUP_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into ServiceStatus(ServiceStatus, ServiceStatusDescription) values (6, &quot;PausePending&quot;).
        /// </summary>
        internal static string SERVICE_STATUS_DB_SETUP_9 {
            get {
                return ResourceManager.GetString("SERVICE_STATUS_DB_SETUP_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelfInstallingWindowsService.exe.config.
        /// </summary>
        internal static string ServiceConfigFile {
            get {
                return ResourceManager.GetString("ServiceConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelfInstallingWindowsService.exe.
        /// </summary>
        internal static string ServiceFile {
            get {
                return ResourceManager.GetString("ServiceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to net.tcp://{0}:{1}/.
        /// </summary>
        internal static string ServiceURLFormat {
            get {
                return ResourceManager.GetString("ServiceURLFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to net.tcp://{0}:{1}/mex/.
        /// </summary>
        internal static string ServiceWSDLFormat {
            get {
                return ResourceManager.GetString("ServiceWSDLFormat", resourceCulture);
            }
        }
    }
}
